### DISCUSSION TITLE
Ingress - Nginx only?

### DISCUSSION THREAD

**Discussion by ksully-execute** [JanssenProject/jans#5600] [General]
I see that nginx-ingress is explicit in the helm chart, but will the project support other ingresses? (I use Cilium)
Perhaps there's a way to override the ingress class?

**Comment by moabu** [comment]
Yes . [This](https://github.com/JanssenProject/jans/blob/a5337bd427903ebef5b65136ed14af2948b002bc/charts/janssen/values.yaml#L853) was added as we changed the annotation for the ingress class name and depreciated that value from our charts .  You may change the ingress class name and it should work in Cilium.  

The above change is supposed in > 1.0.15 charts including 1.0.16-dev chart

**Reply by ksully-execute** [reply]
noted that the new section you highlighted 
```
    ingressClassName: nginx
    path: /
    hosts:
      - demoexample.jans.io
    # -- Secrets holding HTTPS CA cert and key.
    tls:
      - secretName: tls-certificate
        hosts:
          - demoexample.jans.io

```
is still sitting under : 
```
nginx-ingress:
  ingress:

````
Just thought I'd mention it :)
