### ISSUE TITLE
refactor(jans-cedarling)!: implement a new approach for entity mapping

### ISSUE THREAD

**Issue by rmarinn** [JanssenProject/jans#11303]
Following initial internal usage, we've identified a few key areas of confusion and limitations:

- Config usability: The current configuration setup is unclear and can be difficult to work with.
- Entity creation limitations:
    - Only role entities can currently act as parents to other entities.
    - There's no support for defining other types of entities (e.g., scope) that could also serve as parents

We can likely address the first issue with clearer documentation. However, the second issue is more complex and may require a deeper design change to resolve.

Consider the following approach:

### Proposed new `policy_store.yml`

Yes, YAML instead of JSON. Why? This is an approach that's a bit inspired by writing a GitHub workflow. But instead of writing steps for a runner to execute, we write steps for creating a Cedar entity.

```yml
id: this_is_the_policy_store_id
cedar_version: 4.0.0

pipeline:

# Step 1
- issuer.foo:
    uri: https://foo.com/
    desc: Define a source of JWTs
    openid_config_endpoint: https://foo.com/.well-known/openid-configuration
    tokens:
      - access_token
      - id_token
      - userinfo_token

# Step 2
- preprocess.collect.combined_roles:
    desc: Combine 'role' claims from id_token and userinfo_token
    inputs:
      - foo.id_token.role
      - foo.userinfo_token.role

# Step 3
- preprocess.regex_capture.split_email:
    desc: Extract user ID and domain from the email field using regex
    input: foo.userinfo_token.email
    regex: ^(?P<uid>[a-zA-Z0-9._%+-]+)@(?P<domain>[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})$

# Step 4
- preprocess.matrix.role_ids:
    desc: Construct a list of role IDs from id_token and userinfo_token roles
    inputs:
      - foo.id_token.role
      - foo.userinfo_token.role

# Step 5
- preprocess.get_first_available.workload_id:
    desc: Pick the first available value for workload ID
    inputs:
      - foo.access_token.aud
      - foo.userinfo_token.sub

# Step 6
- preprocess.get_first_available.user_id:
    desc: Picks the first available value for the user ID 
    inputs:
      - foo.access_token.aud
      - foo.userinfo_token.sub

# Step 7
- preprocess.get_first_available.spiffe_id:
    desc: Pick the first available value for the SPIFFE ID
    inputs:
      - foo.access_token.client_id
      - foo.access_token.aud

# Step 8
- entity.access_token:
    desc: Create the Access Token entity
    type: Jans::Access_token
    id_src: foo.access_token.jti
    attrs:
      - iss: foo.access_token.iss
      - aud: foo.access_token.aud
      - exp: foo.access_token.exp

# Step 9
- entity.workload:
    desc: Create the Workload entity
    type: Jans::User
    id_src: preprocess.workload_id
    attrs:
      - aud: foo.access_token.aud
        required: false
      - client_id: foo.access_token.client_id
        required: false
      - spiffe_id: preprocess.spiffe_id
      - access_token: entity.access_token

# Step 10
- entity.id_token:
    desc: Create the ID Token entity
    type: Jans::id_token
    id_src: foo.id_token.jti
    attrs_src:
      iss: foo.id_token.iss 
      sub: foo.id_token.sub
      exp: foo.id_token.exp

# Step 11
- entity.userinfo_token:
    desc: Create the Userinfo Token entity
    type: Jans::Userinfo_token
    id_src: foo.userinfo_token.jti
    attrs_src:
      iss: foo.access_token.iss 
      sub: foo.id_token.sub
      exp: foo.access_token.exp

# Step 12
- entity.roles:
    desc: Create the Role entites
    type: Jans::Role
    id_src: preprocess.role_ids

# Step 13
- preprocess.collect.role_entities:
    desc: Collects the role entities from the matrix output into a single array
    inputs:
      - entity.roles

# Step 14
- entity.user:
    desc: Create the User entity
    type: Jans::User
    id_src: foo.userinfo_token.sub
    parents:
      - roles
    attrs:
      - email: preprocess.split_email
      - roles: preprocess.combined_roles
      - id_token: entity.id_token
      - userinfo_token: entity.userinfo_token

policies:

    this_is_the_policy_id:
      description: 'allow admin to see the admin dashboard'
      creation_date: '2024-11-05T02:52:09.488528'
      policy_content: |
        permit (
          principal in Jans::Role::"Read",
          action in [Action:"Monitor"],
          resource in Jans::Http_Request::"/admin_dashboard"
        );

    another_policy_id:
      description: 'allow user to see the user dashboard'
      creation_date: '2024-11-05T02:52:09.488529'
      policy_content: |
        permit (
          principal in Jans::Role::"Read",
          action in [Action:"Monitor"],
          resource in Jans::Http_Request::"/user_dashboard"
        );

schema: |
  ewogICAgInNvbWVjb21wYW55OjpzdG9yZS...
```

The `id`, `cedar_version`, `policies`, and `schema` is pretty much the same as the old implementation. However, we introduce a `pipeline` that describes the steps in JWTs into a Cedar Entity. Since that's a lot to process, let's first go through some overarching design then let's go through the `pipeline`, step-by-step.

#### Design

The `pipeline` is composed of components that we will refer to as *steps*. There are three kinds of steps:

- `issuer`: a step that defines trusted issuers
- `preprocess`: a step that manipulates the inputs and gives an output
- `entity`: a step that builds an entity

`issuer` and `entity` steps is defined as `step_kind.step_id`. For example:

- `issuer.foo`: A step that defines a trusted issuer with the id `foo`.
- `entity.user`: A step that builds a Cedar entity with the id `user`.

`preprocess` steps are defined differently since we need to add a *method name* between the step and the id, e.g. `preprocess.method_name.output_id`. For example:

- `preprocess.collect.combined_roles`: Combines the inputs into a single array and output can be referenced using the id `combined_roles`.

Furthermore, steps can have *inputs* and *outputs*. The inputs and outputs can differ depending on the step. Here's a list of the steps that exist in the example:

1. `issuer` steps:
  - Does not have inputs
  - Outputs are the token claims. You can reference an output using the `step_id.token_name.claim_name`
2. `preprocess.collect` steps:
  - Takes in an array of *strings* or *array of strings*; e.g. `["a", ["b", "c"]]`
  - Outputs a single array
3. `preprocess.regex_capture` steps:
  - Takes in a string as an input
  - Outputs a Key->Value map
4. `preprocess.matrix` steps:
  - Takes in an array of inputs
  - Branches execution, each with one of the inputs as the output.
5. `preprocess.get_first_available` step:
  - Takes in an array of token claims
  - Outputs the first claim that isn't `null` or `undefined`.
6. `entity` steps:
  - Uses claims or `preprocess` outputs to build a Cedar entity.
  - These are the last step of the pipeline for an Entity so it has no outputs.
  

Let's now explore some of the steps in the example:

#### Step 1: Defining the Source of the JWTs

```yml
- issuer.foo:
    uri: https://foo.com/
    desc: Define a trusted source of JWTs
    openid_config_endpoint: https://foo.com/.well-known/openid-configuration
    tokens:
      - access_token
      - id_token
      - userinfo_token
```

This step defines a trusted issuer which will be the source of our JWTs. It has 4 fields:

- `uri`: A string of the URI that one would expect to find in the `iss` field of the JWT.
- `desc`: An *optional* description of the step. The `desc` field exists in all the steps and will not affect execution but can be helpful for making error messages or sharing pipelines.
-  `openid_config_endpoint`: An *optional* URL pointing to the `.well-known/openid-configuration`. This can be left empty, `null`, or `undefined`, and the Cedarling should automatically resolve this. However, in the off-chance that an issuer has their config endpoint somewhere funky, we set it here.
- `tokens`: An array of strings, each referring to the name of a token.

#### Step 2: Combines `role` claims from id_token and userinfo_token

```yml
- preprocess.collect.combined_roles:
    desc: Combine 'role' claims from id_token and userinfo_token
    inputs:
      - foo.id_token.role
      - foo.userinfo_token.role
```

This step collects the 'role' claims from each input token and outputs a single array containing all of them. 

For example, given the following inputs:

- `foo.id_token.role` = `"Admin"`
- `foo.userinfo_token.role` = `"Editor"`
- `bar.userinfo_token.role` = `["Admin", "User", "Reader"]`

The output is expected to be:

```
["Admin", "Editor", "User", "Reader"]
```

#### Step 3: Extract user ID and domain from the email using regex

```yml
- preprocess.regex_capture.split_email:
    desc: Extract user ID and domain from the email field using regex
    input: foo.userinfo_token.email
    regex: ^(?P<uid>[a-zA-Z0-9._%+-]+)@(?P<domain>[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})$
```

This step uses regex capture groups to split a string into multiple parts. The given example splits the input into two groups:

- `uid`
- `domain`

We can reference each one using `preprocess.step_id.capture_group`. For example:

- `preprocess.split_email.uid`
- `preprocess.split_email.email`

Or we can also reference the whole map if we omit the group name, e.g. `preprocess.split_email`.

#### Step 4: Collecting the roles into a single array

```yml
- preprocess.matrix.role_ids:
    desc: Construct a list of role IDs from id_token and userinfo_token roles
    inputs:
      - foo.id_token.role
      - foo.userinfo_token.role
```

This step constructs a list of unique role IDs by combining roles from both the id_token and userinfo_token. The `preprocess.matrix` helps avoid redundancy when trying to create multiple entities with the same ID.

Let's say the given example has the following inputs:

- `foo.id_token.role` = `Admin`
- `foo.userinfo_token.role` = `["Editor", "User"]`
- `bar.userinfo_token.role` = `["Admin", "Creator"]`

The step will build the following array:

```
["Admin", "Editor", "User", "Creator"]
```

Then branch the pipeline into 4, one branch for each output.

#### Step 5, 6, and 7: Get the first available claim (or input)

```yml
- preprocess.get_first_available.workload_id:
    desc: Pick the first available value for workload ID
    inputs:
      - foo.access_token.aud
      - foo.userinfo_token.sub
```

The `preprocess.get_first_available` simply returns the first input that isn't `null`, `undefine`, or an empty string. This is helpful for implementing a fallback if a source might be missing.

#### Step 8, 9, 10, and 11: Creating an entity

These steps are all similar and (hopefully) straightforward so let's focus on one step:

```yml
- entity.access_token:
    desc: Create the Access Token entity
    type: Jans::Access_token
    id_src: foo.access_token.jti
    attrs:
      - iss: foo.access_token.iss
      - aud: foo.access_token.aud
      - exp: foo.access_token.exp
```

Each `entity` step will expect the following inputs:

- `desc`: An *optional* description of the step
- `type`: The type of the Cedar entity to be created
- `id_src`: What we will use as the entity ID
- `parents`: An *optional* field that takes in a list of entities. I'll talk about this on the [next step](#step-11-12-and-13-matrixd-entities) but on this example, it's not supplied.
- `attrs`: A list of (*Cedar attribute name*: *source*). Used to tell the Cedarling which sources to use for each attribute.

After each `entity` step, Entities are expected to be created internally in the Cedarling's state. We can create entity references by referencing the `step_id` after the entity is created. For example:

```yml
- entity.after_access_token:
    type: Jans::Workload
    id_src: foo.access_token.aud
    attrs: 
      - access_token: entity.access_token
```

#### Step 11, 12 and 13: Matrix'd entities

Step 12 is different from the other cases such that multiple entities are being created since it's `id_src` is the output of a `preprocess.matrix`.

However, we don't want to create multiple `Jans::User` entities; thus, we first collect the output roles into a single array before passing it in as the `parent` of `entity.user`.

```yml
# Step 12
- entity.roles:
    desc: Create the Role entites
    type: Jans::Role
    id_src: preprocess.role_ids

# Step 13
- preprocess.collect.role_entities:
    desc: Collects the role entities from the matrix output into a single array
    inputs:
      - entity.roles

# Step 14
- entity.user:
    desc: Create the User entity
    type: Jans::User
    id_src: foo.userinfo_token.sub
    parents:
      - roles
    attrs:
      - email: preprocess.split_email
      - roles: preprocess.combined_roles
      - id_token: entity.id_token
      - userinfo_token: entity.userinfo_token
```

---

### Important Questions To Ask

There are some obvious questions that arise with the design of the `pipeline`. I will try to answer the ones I can think of in this section.

#### 1. Are steps maps with only one key?

Yes. This step:

```yml
- issuer.foo:
    uri: https://foo.com/
    desc: Define a source of JWTs
    openid_config_endpoint: https://foo.com/.well-known/openid-configuration
    tokens:
      - access_token
      - id_token
      - userinfo_token
```

Will look like this in JSON:

```json
[
  {
    "issuer.foo": {
      "uri": "https://foo.com/",
      "desc": "Define a trusted source of JWTs",
      "openid_config_endpoint": "https://foo.com/.well-known/openid-configuration",
      "tokens": [
        "access_token",
        "id_token",
        "userinfo_token"
      ]
    }
  }
]
```

So why maps with single keys? 

First consider this alternative:

```yml
- issuer.foo:
  uri: https://foo.com/
  desc: Define a source of JWTs
  openid_config_endpoint: https://foo.com/.well-known/openid-configuration
  tokens:
    - access_token
    - id_token
    - userinfo_token
```

This is unusable since we're defining `issuer.foo = null`. how do we get the step kind and id?

So let's create a `step_type` and `step_id` field then?

```yml
- step_kind: issuer
  step_name: foo
  uri: https://foo.com/
  desc: Define a source of JWTs
  openid_config_endpoint: https://foo.com/.well-known/openid-configuration
  tokens:
    - access_token
    - id_token
    - userinfo_token
```

Now try doing that multiple times:

```yml
pipeline:
  - step_kind: issuer
    step_id: foo
    uri: https://foo.com/
    desc: Define a source of JWTs
    openid_config_endpoint: https://foo.com/.well-known/openid-configuration
    tokens:
      - access_token
      - id_token
      - userinfo_token

  - step_kind: preprocess.collect
    step_id: combined_roles
    desc: Combine 'role' claims from id_token and userinfo_token
    inputs:
      - foo.id_token.role
      - foo.userinfo_token.role

  - step_kind: entity
    step_id: access_token
    desc: Create the Access Token entity
    type: Jans::Access_token
    id_src: foo.access_token.jti
    attrs:
      - iss: foo.access_token.iss
      - aud: foo.access_token.aud
      - exp: foo.access_token.exp
```

Now our config is full of boilerplate and it's hard to distinguish between step kinds.

#### **How do we require JWT claims?**

Claims used to create entities will be automatically required if they're used as an id or attribute source unless they're an optional attribute:

```yml
pipeline:
  # Required claims: jti, iss
  - access_token:
    - type: Jans::Access_token
    - id_src: access_token.jti
    - attrs:
      - iss: access_token.iss
      - exp: ipd1.access_token.exp
        required: false
```

We should no longer think if the JWT has a `some_random_claim` or not since if we won't even use it to build our entities, we will probably not need it in the policies. So what do we lose by not validating if they're present?

#### **How do we validate JWT claims?**

*Registered claims*[^list_of_registered_claims] used to as entity attributes will be validated.

Validation entails: 

- Requiring the claim
- If the claim is one of the following: 
    `exp`, `nbf`
    they will be validated against the current timestamp.

[^list_of_registered_claims]: Currently, [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1) defines the following registered claims: `iss`, `sub`, `aud`, `exp`, `nbf`, `iat`, `jti`.

To toggle the validation of the `exp`, and `nbf` claims, we will also introduce a new bootstrap property `CEDARLING_JWT_CLAIM_VALIDATION` which defaults to `enabled`.

However, this bootstrap property will not affect required claims. Required claims will still be required if `CEDARLING_JWT_CLAIM_VALIDATION` is `disabled` since we will not be able to the entities.

#### **How do we validate JWT signatures?**

This change will not affect the current behavior of JWT signature validation. Signature validation can sill be toggled using the bootstrap property `CEDARLING_JWT_SIG_VALIDATION`.

Alternatively, we can add this to the `issuer` step but I think using a bootstrap property is cleaner so we don't mix the validation with the pipeline.

```yml
- issuer.foo:
    uri: https://foo.com/
    desc: Define a source of JWTs
    openid_config_endpoint: https://foo.com/.well-known/openid-configuration
    tokens:
      - access_token
      - id_token
      - userinfo_token
    validate_sig: false
```

#### What about the `trusted` flag in the tokens_metadata before?

We can do this:

```yml
- issuer.foo:
    uri: https://foo.com/
    desc: Define a source of JWTs
    openid_config_endpoint: https://foo.com/.well-known/openid-configuration
    tokens:
      - access_token:
          trusted: false
      - id_token:
      - userinfo_token:
    validate_sig: false
    trusted: false # and we can probably toggle the issuer too
```

But isn't it simpler to just remove it from the list?
