### ISSUE TITLE
feat(docker-jans-configurator): templify all configuration and secret keys

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#1266]
To add visibility and documentation automation to the generated configuration and secret parameters we should generate a json pertaining the keys holding its description, example value, and object. This will eliminate the direct hard coded keys and provide a central place to look at when needed. We can abstract the keys by a parent such as `passport`, `couchbase`, `scim` ...etc so that the functions creating these keys aren't changed.

We can call this file `configurator-keys.json`. This file also can be `yaml`.

Example: 

```json
{
  "config": {
    "description": "Holds non-secretive configuration keys and values",
    "keys": {
      "scim": {
        "description": "Holding keys pertaining to the scim service",
        "keys": {
          "scim_rp_client_jwks_fn": {
            "description": "The SCIM Requesting Party client JWKS filename generated in the configuration layer and associated inside the container with the listed file.",
            "file": "/etc/certs/scim-rp-keys.json",
            "encodeType": "None",
            "exampleValue": "/etc/certs/scim-rp-keys.json"
          },
          "scim_rp_client_id": {
            "description": "The SCIM Requesting Party client ID generated in the configuration layer.",
            "file": "",
            "encodeType": "None",
            "exampleValue": "1202.4099a09e-f300-4fa8-8cfd-cb1347149652"
          }
        }
      }
    }
  },
  "secret": {
    "description": "Holds secretive configuration keys and values",
    "keys": {
      "scim": {
        "description": "Holding keys pertaining to the scim service",
        "keys": {
          "scim_rp_client_base64_jwks": {
            "description": "The SCIM Requesting Party client generated JWKS secret in the secret layer and associated inside the container with  the listed file.",
            "file": "/etc/certs/scim-rp-keys.json",
            "encodeType": "None",
            "exampleValue": "ASDUYHzkjxzhcHAIU76y8a9D"
          }
        }
      },
      "ssl": {
        "description": "Holding keys pertaining ssl/https",
        "keys": {
          "ssl_cert": {
            "description": "The SSL of the FQDN chosen by the user, this maybe an automatically generated self signed certificate if the FQDN provided is not reached or not mounted. This is saved in the secret layer and associated inside the container with the listed file",
            "file": "/etc/certs/gluu_https.crt",
            "encodeType": "base64",
            "exampleValue": "MIIFKzCCBNCgAwIBAgIQBqQkCRhyqSfBs9rfkEGNwTAKBggqhkjOPQQDAjBKMQswCQYDVQQGEwJVUzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEgMB4GA1UEAxMXQ2xvdWRmbGFyZSBJbmMgRUNDIENBLTMwHhcNMjExMjIwMDAwMDAwWhcNMjIxMjIwMjM1OTU5WjB1MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEeMBwGA1UEAxMVc25pLmNsb3VkZmxhcmVzc2wuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEU7dAlfSGvvt3Uir5cs3"
          }
        }
      }
    }
  }
}
```

Or perhaps yaml

```yaml
config:
  description: Holds non-secretive configuration keys and values
  keys:
    scim:
      description: Holding keys pertaining to the scim service
      keys:
        scim_rp_client_jwks_fn:
          description: The SCIM Requesting Party client JWKS filename generated in
            the configuration layer and associated inside the container with the listed
            file.
          file: "/etc/certs/scim-rp-keys.json"
          encodeType: None
          exampleValue: "/etc/certs/scim-rp-keys.json"
        scim_rp_client_id:
          description: The SCIM Requesting Party client ID generated in the configuration
            layer.
          file: ''
          encodeType: None
          exampleValue: 1202.4099a09e-f300-4fa8-8cfd-cb1347149652
secret:
  description: Holds secretive configuration keys and values
  keys:
    scim:
      description: Holding keys pertaining to the scim service
      keys:
        scim_rp_client_base64_jwks:
          description: The SCIM Requesting Party client generated JWKS secret in the
            secret layer and associated inside the container with  the listed file.
          file: "/etc/certs/scim-rp-keys.json"
          encodeType: None
          exampleValue: ASDUYHzkjxzhcHAIU76y8a9D
    ssl:
      description: Holding keys pertaining ssl/https
      keys:
        ssl_cert:
          description: The SSL of the FQDN chosen by the user, this maybe an automatically
            generated self signed certificate if the FQDN provided is not reached
            or not mounted. This is saved in the secret layer and associated inside
            the container with the listed file
          file: "/etc/certs/gluu_https.crt"
          encodeType: base64
          exampleValue: MIIFKzCCBNCgAwIBAgIQBqQkCRhyqSfBs9rfkEGNwTAKBggqhkjOPQQDAjBKMQswCQYDVQQGEwJVUzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEgMB4GA1UEAxMXQ2xvdWRmbGFyZSBJbmMgRUNDIENBLTMwHhcNMjExMjIwMDAwMDAwWhcNMjIxMjIwMjM1OTU5WjB1MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEeMBwGA1UEAxMVc25pLmNsb3VkZmxhcmVzc2wuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEU7dAlfSGvvt3Uir5cs3
```
