### ISSUE TITLE
unable to get list of existing couchbase configuration

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#1766]
**Describe the bug**
unable to get list of existing couchbase configuration,getting attached screenshot error

**To Reproduce**
1. open jans-cli
2. oepn config-cli.py
3. select 7 for database
4. select 2 for couchbase 
5. select 1 for get list of couchbase configuraiton

**Expected behavior**
should get list of couchbase configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/178433999-5c0faf16-fe73-4d17-af10-b5d06b16d228.png)

**Desktop (please complete the following information):**
  - OS: [ubuntu]
  - Version [20

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
New version works well
![image](https://user-images.githubusercontent.com/6398752/178559554-cf6d7443-a86f-49d9-96d9-6d6493d2cfb9.png)

This is due to swagger-client - Big heacache.

**Comment by devrimyatar** [comment]
It is not clear why config-api returns ldap information

**Comment by devrimyatar** [comment]
@pujavs For couchbase configuration, the schema is 
```
    CouchbaseConfiguration:
      type: object
      required:
        - configId
        - userName
        - userPassword
        - servers
        - defaultBucket
        - buckets
        - passwordEncryptionMethod
        - sslTrustStoreFile
        - sslTrustStorePin
        - sslTrustStoreFormat     
```
as in https://github.com/JanssenProject/jans/blob/main/jans-config-api/docs/jans-config-api-swagger.yaml#L4121-L4133

But config-api returns the following:

```
https --verify=no -A bearer -a eyJraWQiOiIxNGFhYjI1YS0zNmF....CmwPAmPdUjoJLD3HNAxB5COw https://snap.gluu.org/jans-config-api/api/v1/config/database/couchbase
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 126
Content-Type: application/json
Date: Sat, 24 Sep 2022 11:05:54 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.41 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

[
    {
        "configId": "auth_ldap_server",
        "connectTimeout": 0,
        "kvTimeout": 0,
        "queryTimeout": 0,
        "servers": [
            "localhost:1636"
        ],
        "useSSL": true
    }
]
```
