### ISSUE TITLE
fix: jans-cli enumerate endpoint parameters 

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#2516]
**Describe the bug**
No suggestion list provide for enumerated endpoint parameters. For example,

```
  /jans-config-api/api/v1/scopes/type/{type}:
    parameters:
      - schema:
          type: string
          enum:
            - openid
            - dynamic
            - uma
            - spontaneous
            - oauth
        name: type
        in: path
        required: true
        description: Type of the scope. 
 ```

ClI does not suggest anumeration list for this enpoint parameter

![image](https://user-images.githubusercontent.com/6398752/193270773-f8f02ca4-369d-4f77-92fe-b3272711a9bc.png)
