### ISSUE TITLE
fix(docker-jans-loadtesting-jmeter): incorrect reference to OCI image

### ISSUE THREAD

**Issue by iromli** [JanssenProject/jans#4906]
During loadtesting setup, k8s uses invalid reference of loadtesting-jmeter.

```
containers:
  - envFrom:
    - configMapRef:
        name: load-testing-cm
        image: janssenproject/demo_loadtesting:1.0.12_dev
```

The image name should use the [name](https://github.com/JanssenProject/jans/pkgs/container/jans%2Floadtesting-jmeter) found at registry
