### ISSUE TITLE
Support the ability to run persistence to update entries ( add, remove, update)

### ISSUE THREAD

**Issue by iromli** [JanssenProject/jans#681]
Currently the process of updating a configuration file such as https://raw.githubusercontent.com/JanssenProject/docker-jans-persistence-loader/master/templates/jans-auth/dynamic-conf.ob.json is as below:

1. Install janssen
1. Get configuration json:  `select jansConfDyn from jansAppConf where doc_id = 'jans-auth'`
1. Change the json specific fields
1. Update the table with updated json
1. Restart pods

There is a method upon fresh installation which allows to add remove or update any configuration file or template which is listed below. However, this is only applicable to fresh installs and not running installations:

1. Download the original json file
    ```
    wget https://raw.githubusercontent.com/JanssenProject/docker-jans-persistence-loader/master/templates/jans-auth/dynamic-conf.ob.json
    ```
1. Adjust that file as needed.
1. Create a configmap to hold the file:
    ```
    kubectl create cm custom-auth-config -n gluu --from-file=dynamic-conf.ob.json
    ```
1. Inside your override yaml you have the ability to inject additional volumes and volume mounts. Inside the persistence key add the following:
    ```
    persistence:
      volumes:
	  - name: custom-auth-config
	    configMap:
	      name: custom-auth-config
      volumeMounts:
        - name: custom-auth-config
          mountPath: "/app/templates//jans-auth/dynamic-conf.ob.json"
          subPath: dynamic-conf.ob.json
    ```

1. Now you are ready to install with the custom dynamic conf added.
