### ISSUE TITLE
fix(charts): Adding usrEnvs.normal and usrEnvs.secret gives indentation error in auth-server, fido2, and scim.

### ISSUE THREAD

**Issue by misba7** [JanssenProject/jans#9032]
Adding usrEnvs.secret and usrEnvs.normal to override.yaml:
```
auth-server:
  usrEnvs:
    secret:
      test: ing
    normal:
      CN_CONFIG_API_PLUGINS: scim,user-mgt
```
Gives the following error:

`Error: INSTALLATION FAILED: YAML parse error on janssen/charts/auth-server/templates/deployment.yml: error converting YAML to JSON: yaml: line 31: did not find expected key`
